services:
  event_dispatcher:
    class: Symfony\Component\EventDispatcher\EventDispatcher
    shared: true

  order_processor:
    class: Inventory\OrderProcessor
    arguments: ['@event_dispatcher', '@inventory', '@purchase_order_manager', '@logger']
    shared: true

  inventory:
    class: Inventory\Inventory
    shared: true

  purchase_order_manager:
    class: Inventory\PurchaseOrderManager
    arguments: ['@event_dispatcher', '@inventory', '@logger']
    shared: true

  inventory_reporter:
    class: Inventory\InventoryReporter
    arguments: ['@inventory', '@logger']
    shared: true

  logger:
      class: Inventory\Logger
      shared: true
